### PR TITLE
answers questions

### PR DESCRIPTION
**Pull request by glenntippett**
## About
The initial file contained greetings and questions proposed to the user.
This PR aims to answer these questions to prevent future questions from going un-answered

## Changes
Underneath each question there is a response, the response is a plain text string and can be read by reading with your face

## Learnings
The only issues that occurred was thinking about what to write, there are many possible answers so the proposed answers here are only an example of the many possibilities

### CODE REVIEW

**Comment by Tom-Tee** [comment]
LGTM @glenntippett

Happy to merge

**Comment by glenntippett** [comment]
Another thought about maybe accounting for multiple languages? 
Perhaps this can be opened in a separate issue, @Tom-Tee ?

**Comment by Tom-Tee** [comment]
@glenntippett It would be great to get a few other perspectives. 
Can you open a new PU and action this by Friday EOD?

**Comment by glenntippett** [comment]
@Tom-Tee I've just made some small improvements here. 
I've written a Bash script that will check the users' local language and return a greeting in the correct language. 
At the moment there is only en and fr so some work may need to be done here. 

@enitschorn are you open to getting some outside help on this for more translations?

**Comment by glenntippett** [comment]
Bump

**Comment by Tom-Tee** [comment]
Hi Glenn could you please reopen this.

Thanks.

**Pull request closed without merging**
